### ISSUE TITLE
TypeError: handle_join() got an unexpected keyword argument 'handle_rejoin'

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy#1182]
The coordinator is a deConz so the zigpy-deconz library is used.

The issue seems to happen  since a Schneider Wiser Shutter device has been paired.

Not sure how to handle/debug such problem
```
2023-03-17 11:59:26,080 DEBUG   :APS data confirm response for request with id 83: 00
2023-03-17 11:59:26,082 DEBUG   :Request id: 0x53 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=AddressMode.NWK address=0xd1ef endpoint=5>, status: 0x00
2023-03-17 11:59:26,191 DEBUG   :Frame received: 0x0ee3000700aa00
2023-03-17 11:59:26,192 DEBUG   :Received command device_state_changed[<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2023-03-17 11:59:26,193 DEBUG   :Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2023-03-17 11:59:26,194 DEBUG   :Command Command.aps_data_indication (1, <DataIndicationFlags.Always_Use_NWK_Source_Addr: 1>)
2023-03-17 11:59:26,195 DEBUG   :Send: 0x17e3000800010001
2023-03-17 11:59:26,199 DEBUG   :Frame received: 0x17e3002a002300220200000002f77800000001800c00510054ab41ba9e38c1a4f77800affff6d00800cc
2023-03-17 11:59:26,201 DEBUG   :Received command aps_data_indication[35, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 0, <DeconzAddress address_mode=AddressMode.NWK address=0x78f7>, 0, 0, 32769, b'Q\x00T\xabA\xba\x9e8\xc1\xa4\xf7x', 0, 175, 255, 246, 208, 8, 0, -52]
2023-03-17 11:59:26,202 DEBUG   :APS data indication response: [35, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=AddressMode.NWK address=0x0000>, 0, <DeconzAddress address_mode=AddressMode.NWK address=0x78f7>, 0, 0, 32769, b'Q\x00T\xabA\xba\x9e8\xc1\xa4\xf7x', 0, 175, 255, 246, 208, 8, 0, -52]
2023-03-17 11:59:26,204 DEBUG   :Received a packet: ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x78F7), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=None, profile_id=0, cluster_id=32769, data=Serialized[b'Q\x00T\xabA\xba\x9e8\xc1\xa4\xf7x'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-52)
2023-03-17 11:59:26,206 DEBUG   :Discovered IEEE address for NWK=0x78F7: a4:c1:38:9e:ba:41:ab:54
2023-03-17 11:59:26,207 ERROR   :Unexpected error handling the frame
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/zigpy_deconz/uart.py", line 84, in data_received
    self._api.data_received(frame)
  File "/usr/local/lib/python3.9/dist-packages/zigpy_deconz/api.py", line 373, in data_received
    getattr(self, f"_handle_{command.name}")(data)
  File "/usr/local/lib/python3.9/dist-packages/zigpy_deconz/api.py", line 505, in _handle_aps_data_indication
    self._app.handle_rx(
  File "/usr/local/lib/python3.9/dist-packages/zigpy_deconz/zigbee/application.py", line 430, in handle_rx
    self.packet_received(
  File "/usr/local/lib/python3.9/dist-packages/zigpy/application.py", line 837, in packet_received
    self._maybe_parse_zdo(packet)
  File "/usr/local/lib/python3.9/dist-packages/zigpy/application.py", line 824, in _maybe_parse_zdo
    self.handle_join(
TypeError: handle_join() got an unexpected keyword argument 'handle_rejoin'
```

**Comment by pipiche38** [comment]
To be fixed in the  Domoticz-Zigbee plugin
