### ISSUE TITLE
[BUG] zigpy-homeassistant breaks zigpy (has no attribute BaseDataclassMixin)

### ISSUE THREAD

**Issue by Kochise** [zigpy/zigpy#1189]
Hi,

Source : https://pypi.org/project/zigpy-homeassistant/ -> https://github.com/zigpy/zigpy

Fresh `Python` install :

```batch
pip install zigpy
pip install zigpy-cli
pip install zigpy-xbee
pip install zigpy-znp
pip install bellows
pip install zha-quirks
```

Then :

```batch
zigpy
```

Getting :

```batch
Usage: zigpy [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose
  --help         Show this message and exit.

Commands:
  db
  ota
  pcap
  radio
```

But if I also do :

```batch
pip install zigpy-homeassistant
```

Then :

```batch
zigpy
```

Getting :

```batch
Traceback (most recent call last):
  File "D:\TEST\Python\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\TEST\Python\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\TEST\Python\Scripts\zigpy.exe\__main__.py", line 4, in <module>
  File "D:\TEST\Python\lib\site-packages\zigpy_cli\__main__.py", line 1, in <module>
    import zigpy_cli.database  # noqa: F401
  File "D:\TEST\Python\lib\site-packages\zigpy_cli\database.py", line 13, in <module>
    from zigpy_znp.zigbee.application import ControllerApplication
  File "D:\TEST\Python\lib\site-packages\zigpy_znp\zigbee\application.py", line 11, in <module>
    import zigpy.state
  File "D:\TEST\Python\lib\site-packages\zigpy\state.py", line 27, in <module>
    class Key(t.BaseDataclassMixin):
AttributeError: module 'zigpy.types' has no attribute 'BaseDataclassMixin'
```

Suggestion :

If it is unmaintained, please nuke https://pypi.org/project/zigpy-homeassistant/

@rcloran

**Comment by puddly** [comment]
Why install `zigpy-homeassistant`?

**Comment by Kochise** [comment]
Dunno, why not ?

If it's available on Pypi...

**Comment by Hedda** [comment]
> Suggestion :
> 
> If it is unmaintained, please nuke https://pypi.org/project/zigpy-homeassistant/

That is unmaintained and should not be user, instead see readme in this repo for the used pypi projects.

@Adminiuga is listed as maintainer of that abandoned pypy project so maybe he can remove only that project from pypi?
