### ISSUE TITLE
Thread Devices Not available after update to Silicon Labs Multiprotocol 2.4.1

### ISSUE THREAD

**Issue by RaBuAc** [zigpy/zigpy#1318]
Setup: Home Assistant Yellow
 Core 2024.1.1
Supervisor 2023.12.0
Operating System 11.3

After update to HA OS 11.3, HA SV 2023.12.0 and Silicon Labs Multiprotocol 2.4.1 are the Thread devices not any more available.

I have restored my latest backup and could recover operation.

Protocol: Silicon Labs Multiprotocol 2.4.1
--------------------------------------
[21:36:13] INFO: The otbr-web is disabled.
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[21:36:13] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Jan  5 2024 19:49:05) starting
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 2.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.3  (aarch64 / yellow)
 Home Assistant Core: 2024.1.1
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[21:36:16] INFO: Detected Home Assistant Yellow
[21:36:16] INFO: Starting universal-silabs-flasher with /dev/ttyAMA1
2024-01-05 21:36:17 homeassistant universal_silabs_flasher.flash[182] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.1', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2024-01-05 21:36:17 homeassistant universal_silabs_flasher.flasher[182] INFO Triggering Yellow bootloader
Traceback (most recent call last):
  File "/usr/local/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 36, in inner
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 322, in flash
    await flasher.probe_app_type(
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flasher.py", line 196, in probe_app_type
    await self.enter_yellow_bootloader()
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flasher.py", line 97, in enter_yellow_bootloader
    await send_gpio_pattern(
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flasher.py", line 60, in send_gpio_pattern
    await asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flasher.py", line 30, in _send_gpio_pattern
    chip = gpiod.chip(0, gpiod.chip.OPEN_BY_NUMBER)
AttributeError: module 'gpiod.chip' has no attribute 'OPEN_BY_NUMBER'
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (Jan  5 2024 19:49:05) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[21:36:17] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped

Protocol Matter Server 5.0.2
------------------------------------

 result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 779, in GetConnectedDeviceSync
    returnErr.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 458, in read_attribute
    device = await self._resolve_node(node_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 959, in _resolve_node
    return await self._resolve_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 956, in _resolve_node
    raise NodeNotResolving(f"Unable to resolve Node {node_id}") from err
matter_server.common.errors.NodeNotResolving: Unable to resolve Node 1
2024-01-05 21:42:07 core-matter-server chip.DIS[126] ERROR Unexpected timeout: lookup should have been cleaned already.
2024-01-05 21:42:07 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000005]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:07 core-matter-server matter_server.server.client_handler[126] ERROR [547501205520] Error handling message: CommandMessage(message_id='f8795830ad024773890f146cd162b066', command='read_attribute', args={'node_id': 5, 'attribute_path': '1/319486977/319422472'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 947, in _resolve_node
    return await self._call_sdk(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 856, in _call_sdk
    await self.server.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 779, in GetConnectedDeviceSync
    returnErr.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 458, in read_attribute
    device = await self._resolve_node(node_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 959, in _resolve_node
    return await self._resolve_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 956, in _resolve_node
    raise NodeNotResolving(f"Unable to resolve Node {node_id}") from err
matter_server.common.errors.NodeNotResolving: Unable to resolve Node 5
2024-01-05 21:42:07 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000003]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:07 core-matter-server matter_server.server.client_handler[126] ERROR [547501205520] Error handling message: CommandMessage(message_id='73c6cc1894b34d938e3945d71a5f43f5', command='read_attribute', args={'node_id': 3, 'attribute_path': '1/319486977/319422472'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 947, in _resolve_node
    return await self._call_sdk(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 856, in _call_sdk
    await self.server.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 779, in GetConnectedDeviceSync
    returnErr.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 458, in read_attribute
    device = await self._resolve_node(node_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 959, in _resolve_node
    return await self._resolve_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 956, in _resolve_node
    raise NodeNotResolving(f"Unable to resolve Node {node_id}") from err
matter_server.common.errors.NodeNotResolving: Unable to resolve Node 3
2024-01-05 21:42:38 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2024-01-05 21:42:38 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2024-01-05 21:42:38 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2024-01-05 21:42:38 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2024-01-05 21:42:52 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:52 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:52 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000005]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:52 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000003]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-01-05 21:42:55 core-matter-server matter_server.server.device_controller[126] INFO Attempting to resolve node 2... (attempt 2 of 2)
2024-01-05 21:42:55 core-matter-server matter_server.server.device_controller[126] INFO Attempting to resolve node 1... (attempt 2 of 2)
2024-01-05 21:42:55 core-matter-server matter_server.server.device_controller[126] INFO Attempting to resolve node 5... (attempt 2 of 2)
2024-01-05 21:42:55 core-matter-server matter_server.server.device_controller[126] INFO Attempting to resolve node 3... (attempt 2 of 2)

**Comment by puddly** [comment]
This is not a zigpy issue: https://github.com/home-assistant/addons/issues/3391
