### ISSUE TITLE
Error with latest zigpy -, failed to initialize due to unexpected error -  AttributeError: 'AnonymousLVList' object has no attribute 'is_end_device'

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy#1390]
With the latest zigpy version I'm getting this error. Reverting to previous one
```
2024-04-24 20:13:12,940 WARNING :Device <Device model=None manuf=None nwk=0x88E4 ieee=00:04:74:00:00:82:a5:4f is_initialized=False> failed to initialize due to unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 205, in initialize
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    return await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 234, in _initialize
    status, _, endpoints = await self.zdo.Active_EP_req(self.nwk)
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 314, in request
    if expect_reply and (self.node_desc is None or self.node_desc.is_end_device):
AttributeError: 'AnonymousLVList' object has no attribute 'is_end_device'
2024-04-24 20:13:12,996 WARNING :Device <Device model=None manuf=None nwk=0x88E4 ieee=00:04:74:00:00:82:a5:4f is_initialized=False> failed to initialize due to unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 205, in initialize
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    return await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 234, in _initialize
    status, _, endpoints = await self.zdo.Active_EP_req(self.nwk)
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 314, in request
    if expect_reply and (self.node_desc is None or self.node_desc.is_end_device):
AttributeError: 'AnonymousLVList' object has no attribute 'is_end_device'
2024-04-24 20:13:13,225 INFO    :b'Unknown Window Covering Command: 06'
2024-04-24 20:13:13,268 WARNING :Device <Device model=None manuf=None nwk=0x88E4 ieee=00:04:74:00:00:82:a5:4f is_initialized=False> failed to initialize due to unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 205, in initialize
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    return await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 234, in _initialize
    status, _, endpoints = await self.zdo.Active_EP_req(self.nwk)
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 314, in request
    if expect_reply and (self.node_desc is None or self.node_desc.is_end_device):
AttributeError: 'AnonymousLVList' object has no attribute 'is_end_device'
```

**Comment by TheJulianJES** [comment]
So, 0.63.5 is fine, but 0.64.0 is broken for you?

**Comment by pipiche38** [comment]
> So, 0.63.5 is fine, but 0.64.0 is broken for you?

Correct. No error with 

```
zigpy==0.63.5
zigpy_znp==0.12.1
zigpy_deconz==0.23.1
bellows==0.38.1
```

**Comment by TheJulianJES** [comment]
I'm seeing no changes in that version that would affect this.

What device is this?
`Device model=None manuf=None nwk=0x88E4 ieee=00:04:74:00:00:82:a5:4f`

**Comment by pipiche38** [comment]
problem occured, when pairing a new device.
The device here showing the error is a 'Dimmer switch wo neutral' from Legrand

**Comment by pipiche38** [comment]
Did get the same error with an INNR SP120 plug. Unfortunatly as soon as I enable the full zigpy _ bellows logs I'm not getting any more

**Comment by TheJulianJES** [comment]
Are you sure this is caused by the zigpy dependency bump and not by bellows [0.38.2](https://github.com/zigpy/bellows/releases/tag/0.38.2)?

**Comment by pipiche38** [comment]
> Are you sure this is caused by the zigpy dependency bump and not by bellows [0.38.2](https://github.com/zigpy/bellows/releases/tag/0.38.2)?

Indeed I'm upgrading both zigpy and bellows

**Comment by TheJulianJES** [comment]
So, just upgrade zigpy by itself, check again, and then only update bellows by itself to check where the problem originates from.

**Comment by pipiche38** [comment]
not able to duplicate on zigpy 0.64.0.
So I'll just upgrade the zigpy layer and wait for a more stable bellows part
