### ISSUE TITLE
OTA fails for ThirdReality 3RSP02028BZ metering outlet

### ISSUE THREAD

**Issue by keepiru** [zigpy/zigpy#1401]
I've been upgrading my 3RSP02028BZ devices from 0x1001304f to 0x10013050.  OTA upgrade seems to work fine (progress meter increasing) through the UI but then stops partway through and reverts to the "skip | install" selections.  If I click "install" again it will pick up where it left off, and eventually complete.

This time I tuned on some logging to hopefully create a useful bug report.  Logs saved, excerpt attached.  I'm keeping it in the half-upgraded state in case there's additional testing you'd like for me to perform.

```
logger:
  default: info
  logs:
    homeassistant.components.bluetooth: debug
    homeassistant.components.zha: debug
    zigpy: debug
```

```
2024-05-13 13:43:20.526 INFO (MainThread) [zigpy.device] [0x1037] OTA upgrade progress: (90840 / 195698): 46.4185%
2024-05-13 13:43:20.540 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 5, 13, 20, 43, 20, 540432, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x1037), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=25, data=Serialized[b'\x01\xa2\x03\x023\x12\xa6\xd3P0\x01\x10\xd8b\x01\x000\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=232, rssi=-74)
2024-05-13 13:43:20.543 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received ZCL frame: b'\x01\xa2\x03\x023\x12\xa6\xd3P0\x01\x10\xd8b\x01\x000\x00\x00'
2024-05-13 13:43:20.545 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x01>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=162, command_id=3, *direction=<Direction.Client_to_Server: 0>)
2024-05-13 13:43:20.550 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame: Ota:ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90840, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.551 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received command 0x03 (TSN 162): ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90840, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.554 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply header: ZCLHeader(frame_control=FrameControl<0x19>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=0, *is_cluster=True, *is_general=False), tsn=162, command_id=5, *direction=<Direction.Server_to_Client: 1>)
2024-05-13 13:43:20.556 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply: ImageBlockResponseCommand(status=<Status.SUCCESS: 0>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90840, image_data=b'i\x06\xfe\x97\x1a\x9e\x06\xa3\x03@0\xec9\xecR\x06\x00\xa3\x00\x90\xba\x9b+Xd\x87\x01\xa0\xda\x97\x0f\x98\xa9\x87\x10p\x84\x00\x00\x1f')
2024-05-13 13:43:20.565 DEBUG (MainThread) [homeassistant.components.zha.entity] sensor.living_room_a_c_active_power: skipping polling for updated state, available: False, allow polled requests: True
2024-05-13 13:43:20.593 INFO (MainThread) [zigpy.device] [0x1037] OTA upgrade progress: (90880 / 195698): 46.4389%
2024-05-13 13:43:20.617 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 5, 13, 20, 43, 20, 617524, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x1037), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=25, data=Serialized[b'\x01\xa3\x03\x023\x12\xa6\xd3P0\x01\x10\x00c\x01\x000\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-74)
2024-05-13 13:43:20.620 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received ZCL frame: b'\x01\xa3\x03\x023\x12\xa6\xd3P0\x01\x10\x00c\x01\x000\x00\x00'
2024-05-13 13:43:20.622 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x01>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=163, command_id=3, *direction=<Direction.Client_to_Server: 0>)
2024-05-13 13:43:20.627 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame: Ota:ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90880, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.628 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received command 0x03 (TSN 163): ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90880, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.631 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply header: ZCLHeader(frame_control=FrameControl<0x19>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=0, *is_cluster=True, *is_general=False), tsn=163, command_id=5, *direction=<Direction.Server_to_Client: 1>)
2024-05-13 13:43:20.632 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply: ImageBlockResponseCommand(status=<Status.SUCCESS: 0>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90880, image_data=b'\x84\x00\xfc\x1e\x84\x00\x04p\x84\x00\xack\x84\x00\x03\xc8\xff\xff\x03\xc8\x00\x00\x02\x0bZL\x01\xb2ZDp\x07\xc0F\x10p\x84\x00\x01\xa2')
2024-05-13 13:43:20.660 DEBUG (MainThread) [zigpy.device] [0x1037] OTA image_block handler exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zigpy/ota/manager.py", line 152, in _image_block_req
    await self.ota_cluster.image_block_response(
  File "/usr/local/lib/python3.12/site-packages/zigpy/zcl/__init__.py", line 415, in reply
    return await self._endpoint.reply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/endpoint.py", line 290, in reply
    return await self.device.reply(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 508, in reply
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 334, in request
    await send_request()
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 841, in request
    await self.send_packet(
  File "/usr/local/lib/python3.12/site-packages/zigpy_deconz/zigbee/application.py", line 530, in send_packet
    raise zigpy.exceptions.DeliveryError(
zigpy.exceptions.DeliveryError: Failed to deliver packet: <TXStatus.APS_NO_ACK: 167>
2024-05-13 13:43:20.726 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546917017280] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/zha/update.py", line 196, in async_install
    raise HomeAssistantError(f"Update was not successful: {result}")
homeassistant.exceptions.HomeAssistantError: Update was not successful: <Status.FAILURE: 1>
2024-05-13 13:43:20.850 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 5, 13, 20, 43, 20, 850273, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x1037), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=None, profile_id=260, cluster_id=25, data=Serialized[b'\x01\xa4\x03\x023\x12\xa6\xd3P0\x01\x10(c\x01\x000\x00\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-74)
2024-05-13 13:43:20.852 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received ZCL frame: b'\x01\xa4\x03\x023\x12\xa6\xd3P0\x01\x10(c\x01\x000\x00\x00'
2024-05-13 13:43:20.854 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x01>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=164, command_id=3, *direction=<Direction.Client_to_Server: 0>)
2024-05-13 13:43:20.858 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Decoded ZCL frame: Ota:ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90920, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.859 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Received command 0x03 (TSN 164): ImageBlockCommand(field_control=<FieldControl.MinimumBlockPeriod: 2>, manufacturer_code=4659, image_type=54182, file_version=268513360, file_offset=90920, maximum_data_size=48, minimum_block_period=0)
2024-05-13 13:43:20.871 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply header: ZCLHeader(frame_control=FrameControl<0x19>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=0, *is_cluster=True, *is_general=False), tsn=164, command_id=5, *direction=<Direction.Server_to_Client: 1>)
2024-05-13 13:43:20.873 DEBUG (MainThread) [zigpy.zcl] [0x1037:1:0x0019] Sending reply: ImageBlockResponseCommand(status=<Status.ABORT: 149>)
2024-05-13 13:43:23.882 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xBE70](3RTHS24BZ): Device seen - marking the device available and resetting counter
2024-05-13 13:43:23.883 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xBE70](3RTHS24BZ): Update device availability -  device available: True - new availability: True - changed: False
2024-05-13 13:43:23.891 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x596B](3RTHS24BZ): Device seen - marking the device available and resetting counter
2024-05-13 13:43:23.892 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x596B](3RTHS24BZ): Update device availability -  device available: True - new availability: True - changed: False
2024-05-13 13:43:26.514 DEBUG (MainThread) [homeassistant.components.zha.entity] sensor.test_meter_power: skipping polling for updated state, available: False, allow polled requests: True
2024-05-13 13:43:29.664 DEBUG (MainThread) [zigpy.application] Feeding watchdog
2024-05-13 13:43:30.640 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xDF8B](3RTHS24BZ): Device seen - marking the device available and resetting counter
2024-05-13 13:43:30.641 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xDF8B](3RTHS24BZ): Update device availability -  device available: True - new availability: True - changed: False
```

**Comment by the-ress** [comment]
I’m having the same issue with an IKEA Tradfri 5-button remote - the logs look very similar, except it only gets to about 4-5%.
