### ISSUE TITLE
MultiState Input - StateText Array not parsed correctly

### ISSUE THREAD

**Issue by prairiesnpr** [zigpy/zigpy#1446]
Note: This is a custom end device so there is a good chance that I misunderstood the ZCL specification or didn't implement it properly.

On the MulitstateInput, the StateText Cluster defines the type as an ```Array of character string```.  https://zigbeealliance.org/wp-content/uploads/2021/10/07-5123-08-Zigbee-Cluster-Library.pdf#page=68

The data format is defined here: https://zigbeealliance.org/wp-content/uploads/2021/10/07-5123-08-Zigbee-Cluster-Library.pdf#page=65

And the array is further defined here: https://zigbeealliance.org/wp-content/uploads/2021/10/07-5123-08-Zigbee-Cluster-Library.pdf#page=104

My understanding is that given an array of character strings, such as ["Full","Low","Empty"], this should result in a payload as follows.

```b'\x58\x08\x01\x0e\x00\x00\x48\x03\x00\x04Full\x03Low\x05Empty'```

Where ```b'\x58\x08\x01'``` is the ZCL header, leaving a payload of:

```b' \x0e\x00\x00\x48\x03\x00\x04Full\x03Low\x05Empty'```

Corresponding to:

Byte 0-1: Attr Id - 0x0e00
Byte 2: Status - (Success) 0x00 
Byte 3: Data Type (Array) - 0x48 
Byte 4-5: Length of Array (uint16_t) - 0x0300
Byte 6: Length of first character string - 0x04
Byte 7-10: First character string - "Full"
Byte 11: Length of second character string - 0x03
Byte 12-14 Second character string - "Low"
Byte 15: Length of third character string - 0x05
Byte 16-20: Third character string - "Empty"

This fails to parse with the following in the logs.

```
2024-08-13 08:11:56.443 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Sending request header: ZCLHeader(frame_control=FrameControl<0x00>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=11, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Client_to_Server: 0>)
2024-08-13 08:11:56.443 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Sending request: Read_Attributes(attribute_ids=[14])
2024-08-13 08:11:56.444 DEBUG (MainThread) [zigpy_znp.zigbee.application] Sending packet ZigbeePacket(timestamp=datetime.datetime(2024, 8, 13, 12, 11, 56, 444453, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x82C7), dst_ep=1, source_route=None, extended_timeout=False, tsn=11, profile_id=260, cluster_id=18, data=Serialized[b'\x00\x0b\x00\x0e\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2024-08-13 08:11:56.445 DEBUG (MainThread) [zigpy_znp.api] Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x82C7), DstEndpoint=1, DstPanId=0x0000, SrcEndpoint=1, ClusterId=18, TSN=11, Options=<TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK: 32>, Radius=0, Data=b'\x00\x0B\x00\x0E\x00')
2024-08-13 08:11:56.570 DEBUG (MainThread) [zigpy_znp.api] Received command: ZDO.SrcRtgInd.Callback(DstAddr=0x82C7, Relays=[])
2024-08-13 08:11:56.626 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=18, SrcAddr=0x82C7, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=109, SecurityUse=<Bool.false: 0>, TimeStamp=14321961, TSN=0, Data=b'\x58\x0B\x01\x0E\x00\x00\x48\x03\x00\x04\x46\x75\x6C\x6C\x03\x4C\x6F\x77\x05\x45\x6D\x70\x74\x79', MacSrcAddr=0x82C7, MsgResultRadius=29)
2024-08-13 08:11:56.627 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 8, 13, 12, 11, 56, 627547, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x82C7), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=0, profile_id=260, cluster_id=18, data=Serialized[b'X\x0b\x01\x0e\x00\x00H\x03\x00\x04Full\x03Low\x05Empty'], tx_options=<TransmitOptions.NONE: 0>, radius=29, non_member_radius=0, lqi=109, rssi=None)
2024-08-13 08:11:56.628 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Received ZCL frame: b'X\x0b\x01\x0e\x00\x00H\x03\x00\x04Full\x03Low\x05Empty'
2024-08-13 08:11:56.629 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x58>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=2, *is_cluster=False, *is_general=True), tsn=11, command_id=1, *direction=<Direction.Server_to_Client: 1>)
2024-08-13 08:11:56.629 DEBUG (MainThread) [zigpy.device] [0x82c7] Failed to parse packet ZigbeePacket(timestamp=datetime.datetime(2024, 8, 13, 12, 11, 56, 627547, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x82C7), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=0, profile_id=260, cluster_id=18, data=Serialized[b'X\x0b\x01\x0e\x00\x00H\x03\x00\x04Full\x03Low\x05Empty'], tx_options=<TransmitOptions.NONE: 0>, radius=29, non_member_radius=0, lqi=109, rssi=None)
2024-08-13 08:12:16.326 DEBUG (MainThread) [zha.zigbee.device] [0x82C7](Dog Feeder): Device seen - marking the device available and resetting counter
2024-08-13 08:12:16.326 DEBUG (MainThread) [zha.zigbee.device] [0x82C7](Dog Feeder): Update device availability -  device available: True - new availability: True - changed: False
```

Expected state, the response should parse to a valid list.

**Comment by prairiesnpr** [comment]
Ok, so this seems to have two components, one, the above is missing the datatype packet.

It should be.

```
b' \x0e\x00\x00\x42\x48\x03\x00\x04Full\x03Low\x05Empty'

Corresponding to:

Byte 0-1: Attr Id - 0x0e00
Byte 2: Status - (Success) 0x00
Byte 3: Data Type (Array) - 0x48
Byte 4:  Data Type (Char String) - 0x42
Byte 5-6: Length of Array (uint16_t) - 0x0300
Byte 7: Length of first character string - 0x04
Byte 8-11: First character string - "Full"
Byte 12: Length of second character string - 0x03
Byte 13-15 Second character string - "Low"
Byte 16: Length of third character string - 0x05
Byte 17-21: Third character string - "Empty"
```

The second part is that the definition for StateText (https://github.com/zigpy/zigpy/blob/33680a0a9a75b8eb0450a91911793ebd8feb7186/zigpy/zcl/clusters/general.py#L1625) is currently List and should be LVList.

That said though, LVList has ```_length_type = uint8_t``` and should be ```_length_type = uint16_t``` per my understanding of the ZCL spec.  

https://github.com/zigpy/zigpy/blob/33680a0a9a75b8eb0450a91911793ebd8feb7186/zigpy/types/basic.py#L880

Testing those changes results in correctly parsing the packet.

```
2024-08-13 10:16:29.492 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2024, 8, 13, 14, 16, 29, 492246, tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x82C7), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=0, profile_id=260, cluster_id=18, data=Serialized[b'X\x05\x01\x0e\x00\x00HB\x03\x00\x04Full\x03Low\x05Empty'], tx_options=<TransmitOptions.NONE: 0>, radius=29, non_member_radius=0, lqi=87, rssi=None)
2024-08-13 10:16:29.493 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Received ZCL frame: b'X\x05\x01\x0e\x00\x00HB\x03\x00\x04Full\x03Low\x05Empty'
2024-08-13 10:16:29.493 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x58>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=2, *is_cluster=False, *is_general=True), tsn=5, command_id=1, *direction=<Direction.Server_to_Client: 1>)
2024-08-13 10:16:29.494 DEBUG (MainThread) [zigpy.zcl] [0x82C7:1:0x0012] Decoded ZCL frame: MultistateInput:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid=0x000E, status=<Status.SUCCESS: 0>, value=TypeValue(type=Array, value=Array(type=AnonymousLVList, value=['Full', 'Low', 'Empty'])))])
```

But now throws an error in the web socket api.  

```
2024-08-13 10:16:29.495 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [545095748912] Error handling message: Unknown error (unknown_error)---- (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/zha/websocket_api.py", line 861, in websocket_read_zigbee_cluster_attributes
    success, failure = await cluster.read_attributes(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/zigpy/zcl/__init__.py", line 538, in read_attributes
    value = self.attributes[record.attrid].type(record.value.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
