### ISSUE TITLE
SYMFONISK sound remote gen2 - sporadically no commands can be sent 

### ISSUE THREAD

**Issue by Matze89x** [zigpy/zigpy#1506]
Hello to you,

I've had a serious problem since a few updates (unfortunately I can't remember exactly when).

I can't use the remote control all the time. Every 30 minutes it seems to lose the connection for 10 minutes and then it can be reached again normally and the commands are sent to Skyconnect again. However, if I do the identification test, it works in Home Assistant.

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/00bc029a-5757-45b0-aae9-8d4d13401450">
<img width="561" alt="image" src="https://github.com/user-attachments/assets/a9e992f1-9edc-445e-8f37-8ea2d8a3fa2f">

```
It concerns the remote control from Ikea.
SYMFONISK sound remote gen2
from IKEA of Sweden
Installed version - 0x01000035
IEEE: 1c:34:f1:ff:fe:a2:7a:6e
Nwk: 0xcd1c
Device Type: EndDevice
LQI: 196
RSSI: -62

Connected via:
SkyConnect v1.0
from Nabu Casa
Firmware: 7.4.4.0 build 0
```

I have already tried the following:
- Removed all devices (sockets) that also pair with the remote control. 
- Reset the remote control and re-paired it several times. 
- I have already moved the Skyconnect stick to another location using extension cables.
- Paired the remote control via another system as a test
- Already changed channel 25 to 18 for the entire network
- No WLAN interference in the network - everything is OK - other devices (35) work perfectly.
- Also tested a migration from SkyConnect to SONOFF Dongle-E - same problems.
- I paired the remote control on my Linux system with Zigbee2MQTT as a test and used it to forward some commands over the course of a day - no problems. I wanted to know whether the remote control might be faulty.

Here is the protocol that is constantly forming during the day... over 60x
```
Logger: zigpy.zcl
Quelle: runner.py:189
Erstmals aufgetreten: 13:46:54 (10 Vorkommnisse)
Zuletzt protokolliert: 18:22:03

[0xCD1C:1:0x0020] Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zigpy/endpoint.py", line 270, in request return await self.device.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 378, in request await send_request() File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 825, in request await self.send_packet( File "/usr/local/lib/python3.12/site-packages/bellows/zigbee/application.py", line 824, in send_packet raise zigpy.exceptions.DeliveryError( zigpy.exceptions.DeliveryError: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/general.py", line 630, in check_in_response await self.checkin_response(True, self.CHECKIN_FAST_POLL_TIMEOUT, tsn=tsn) File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 84, in wrapper with wrap_zigpy_exceptions(): File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__ self.gen.throw(value) File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 76, in wrap_zigpy_exceptions raise ZHAException(message) from exc zha.exceptions.ZHAException: Failed to send request: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074>
[0xCD1C:1:0x0020] Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 381, in request return await req.result ^^^^^^^^^^^^^^^^ asyncio.exceptions.CancelledError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zigpy/zcl/__init__.py", line 375, in request return await self._endpoint.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/zigpy/endpoint.py", line 270, in request return await self.device.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 380, in request async with asyncio_timeout(timeout): File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__ raise TimeoutError from exc_val TimeoutError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/general.py", line 630, in check_in_response await self.checkin_response(True, self.CHECKIN_FAST_POLL_TIMEOUT, tsn=tsn) File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 84, in wrapper with wrap_zigpy_exceptions(): File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__ self.gen.throw(value) File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 69, in wrap_zigpy_exceptions raise ZHAException("Failed to send request: device did not respond") from exc zha.exceptions.ZHAException: Failed to send request: device did not respond
[0xCD1C:1:0x0020] Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zigpy/endpoint.py", line 270, in request return await self.device.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/zigpy/device.py", line 378, in request await send_request() File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 825, in request await self.send_packet( File "/usr/local/lib/python3.12/site-packages/bellows/zigbee/application.py", line 824, in send_packet raise zigpy.exceptions.DeliveryError( zigpy.exceptions.DeliveryError: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/general.py", line 633, in check_in_response await self.fast_poll_stop() File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 84, in wrapper with wrap_zigpy_exceptions(): File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__ self.gen.throw(value) File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 76, in wrap_zigpy_exceptions raise ZHAException(message) from exc zha.exceptions.ZHAException: Failed to send request: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074>

```

<img width="715" alt="image" src="https://github.com/user-attachments/assets/273caf14-a3c6-4577-bf7c-f2eed8525b30">

I would really appreciate your help. I'm really at a loss as to what's going on here. I'm also watching the visualisation - everything is OK and connects to other sockets in the household from time to time. TS011F
from _TZ3000_u5u4cakc

**Comment by puddly** [comment]
Closing in favor of https://github.com/home-assistant/core/issues/131387.
