### ISSUE TITLE
Failed ZDO request during device initialization - on each startup

### ISSUE THREAD

**Issue by shortbloke** [zigpy/zigpy#277]
Hi,
Whenever I start/re-start my Home Assistant (0.103.6) instance (not sure how to determine what versions of zigpy is included), I'm seeing an error logged:
`ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization`

With debug logging enabled, the device which appears to be causing the error is `Device 0x0000 (00:0d:6f:00:0b:5d:d1:25) joined the network` 
Though I don't see that device in the zigbee database. Any suggestions on what might be going on here and how to fix/avoid the error?

**Debug Logs**
```
2020-01-14 12:56:33 INFO (MainThread) [zigpy.application] Device 0x0000 (00:0d:6f:00:0b:5d:d1:25) joined the network
2020-01-14 12:56:33 INFO (MainThread) [zigpy.device] [0x0000] Requesting 'Node Descriptor'
2020-01-14 12:56:33 DEBUG (MainThread) [zigpy.device] [0x0000] Extending timeout for 0x01 request
2020-01-14 12:56:33 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x0002: [0x0000]
2020-01-14 12:56:33 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x0002
2020-01-14 12:56:33 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x8002: [<Status.SUCCESS: 0>, 0x0000, <Optional byte1=0 byte2=64 mac_capability_flags=143 manufacturer_code=43981 maximum_buffer_size=82 maximum_incoming_transfer_size=128 server_mask=0 maximum_outgoing_transfer_size=128 descriptor_capability_field=0>]
2020-01-14 12:56:33 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x8002
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xbd85](lumi.sensor_magnet.aq2): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:ZDO](lumi.sensor_magnet.aq2): entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sensor_magnet.aq2', ieee='00:15:8d:00:03:67:3f:64', last_seen=1579005693.6829133)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:ZDO](lumi.sensor_magnet.aq2): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x1049](lumi.sensor_magnet.aq2): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:ZDO](lumi.sensor_magnet.aq2): entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sensor_magnet.aq2', ieee='00:15:8d:00:02:75:33:5b', last_seen=1579005954.4387465)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:ZDO](lumi.sensor_magnet.aq2): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xbd85](lumi.sensor_magnet.aq2): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xbd85](lumi.sensor_magnet.aq2): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x1049](lumi.sensor_magnet.aq2): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x1049](lumi.sensor_magnet.aq2): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xa42f](lumi.sensor_magnet.aq2): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:ZDO](lumi.sensor_magnet.aq2): entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sensor_magnet.aq2', ieee='00:15:8d:00:02:53:70:bc', last_seen=1579004205.7426288)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:ZDO](lumi.sensor_magnet.aq2): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x5e3c](lumi.sensor_magnet.aq2): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:ZDO](lumi.sensor_magnet.aq2): entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sensor_magnet.aq2', ieee='00:15:8d:00:02:75:32:10', last_seen=1579003987.6159956)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:ZDO](lumi.sensor_magnet.aq2): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xa42f](lumi.sensor_magnet.aq2): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xa42f](lumi.sensor_magnet.aq2): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x5e3c](lumi.sensor_magnet.aq2): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x5e3c](lumi.sensor_magnet.aq2): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb484](lumi.sensor_magnet): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:ZDO](lumi.sensor_magnet): entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sensor_magnet', ieee='00:15:8d:00:03:03:3d:99', last_seen=1579005015.1820223)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:ZDO](lumi.sensor_magnet): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe726](lumi.sensor_ht): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:ZDO](lumi.sensor_ht): entry loaded from storage: ZhaDeviceEntry(name='None lumi.sensor_ht', ieee='00:15:8d:00:02:37:8a:ca', last_seen=1579006335.1590543)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:ZDO](lumi.sensor_ht): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0006]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0006]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0008]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0008]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0005]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0005]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0402]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0402]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0405]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0405]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0005]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:1:0x0005]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:2:0x0005]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:2:0x0005]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:3:0x0005]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe726:3:0x0005]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb484](lumi.sensor_magnet): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb484](lumi.sensor_magnet): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe726](lumi.sensor_ht): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe726](lumi.sensor_ht): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x4879](RH3040): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:ZDO](RH3040): entry loaded from storage: ZhaDeviceEntry(name='TUYATEC-zn9wyqtr RH3040', ieee='ec:1b:bd:ff:fe:78:31:0a', last_seen=1579006556.9415984)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:ZDO](RH3040): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xf488](RH3040): started initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:ZDO](RH3040): entry loaded from storage: ZhaDeviceEntry(name='TUYATEC-zn9wyqtr RH3040', ieee='ec:1b:bd:ff:fe:78:3a:89', last_seen=1579004249.446113)
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:ZDO](RH3040): channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0000]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0000]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0001]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0001]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0500]: initializing channel: from_cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xf488:1:0x0500]: channel: 'async_initialize' stage succeeded
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x4879](RH3040): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x4879](RH3040): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xf488](RH3040): power source: Battery or Unknown
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xf488](RH3040): completed initialization
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xbd85:1:0x0006]: attempting to update onoff state - from cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x1049:1:0x0006]: attempting to update onoff state - from cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xa42f:1:0x0006]: attempting to update onoff state - from cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x5e3c:1:0x0006]: attempting to update onoff state - from cache: True
2020-01-14 12:56:33 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb484:1:0x0006]: attempting to update onoff state - from cache: True
2020-01-14 12:56:37 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Temperature (Morgan): UndefinedError: 'mappingproxy object' has no attribute 'Temperature'
2020-01-14 12:56:37 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Temperature (Conservatory): UndefinedError: 'mappingproxy object' has no attribute 'Temperature'
2020-01-14 12:56:37 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Temperature (Fraser): UndefinedError: 'mappingproxy object' has no attribute 'Temperature'
2020-01-14 12:56:37 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Temperature (Living Room): UndefinedError: 'mappingproxy object' has no attribute 'Temperature'
2020-01-14 12:56:56 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: Updated alarm state: 0
2020-01-14 12:56:57 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: Updated alarm state: 0
2020-01-14 12:57:02 DEBUG (MainThread) [zigpy.device] [0x0000] Extending timeout for 0x04 request
2020-01-14 12:57:02 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x0002: [0x0000]
2020-01-14 12:57:02 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x0002
2020-01-14 12:57:02 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x8002: [<Status.SUCCESS: 0>, 0x0000, <Optional byte1=0 byte2=64 mac_capability_flags=143 manufacturer_code=43981 maximum_buffer_size=82 maximum_incoming_transfer_size=128 server_mask=0 maximum_outgoing_transfer_size=128 descriptor_capability_field=0>]
2020-01-14 12:57:02 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x8002
2020-01-14 12:57:30 WARNING (MainThread) [zigpy.device] [0x0000] Requesting Node Descriptor failed: 
2020-01-14 12:57:30 INFO (MainThread) [zigpy.device] [0x0000] Discovering endpoints
2020-01-14 12:57:30 DEBUG (MainThread) [zigpy.device] [0x0000] Extending timeout for 0x06 request
2020-01-14 12:57:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x0005: [0x0000]
2020-01-14 12:57:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x0005
2020-01-14 12:57:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x8005: [<Status.SUCCESS: 0>, 0x0000, [1]]
2020-01-14 12:57:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x8005
2020-01-14 12:57:38 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: Updated alarm state: 1
2020-01-14 12:57:39 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0x4879:1:0x0500]: Updated alarm state: 1
2020-01-14 12:58:00 DEBUG (MainThread) [zigpy.device] [0x0000] Extending timeout for 0x08 request
2020-01-14 12:58:00 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x0005: [0x0000]
2020-01-14 12:58:00 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x0005
2020-01-14 12:58:00 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x8005: [<Status.SUCCESS: 0>, 0x0000, [1]]
2020-01-14 12:58:00 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x8005
2020-01-14 12:58:30 DEBUG (MainThread) [zigpy.device] [0x0000] Extending timeout for 0x0a request
2020-01-14 12:58:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x0005: [0x0000]
2020-01-14 12:58:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x0005
2020-01-14 12:58:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request 0x8005: [<Status.SUCCESS: 0>, 0x0000, [1]]
2020-01-14 12:58:30 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] Unsupported ZDO request:0x8005
2020-01-14 12:58:58 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 86, in _initialize
    epr = await self.zdo.Active_EP_req(self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.7/site-packages/zigpy/util.py", line 88, in retry
    r = await func()
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 191, in request
    result = await asyncio.wait_for(req.result, timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2020-01-14 13:03:21 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [ec:1b:bd:ff:fe:78:3a:89] bindable devices:: [[]]
2020-01-14 13:03:26 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:02:37:8a:ca] bindable devices:: [[]]
2020-01-14 13:03:31 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:03:67:3f:64] bindable devices:: [[]]
2020-01-14 13:03:37 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [ec:1b:bd:ff:fe:78:3a:89] bindable devices:: [[]]
2020-01-14 13:03:39 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [ec:1b:bd:ff:fe:78:31:0a] bindable devices:: [[]]
2020-01-14 13:03:40 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:03:67:3f:64] bindable devices:: [[]]
2020-01-14 13:03:42 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:02:75:33:5b] bindable devices:: [[]]
2020-01-14 13:03:44 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:02:53:70:bc] bindable devices:: [[]]
2020-01-14 13:03:46 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:02:75:32:10] bindable devices:: [[]]
2020-01-14 13:03:48 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:03:03:3d:99] bindable devices:: [[]]
2020-01-14 13:03:50 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [00:15:8d:00:02:37:8a:ca] bindable devices:: [[]]
2020-01-14 13:03:56 DEBUG (MainThread) [homeassistant.components.zha.api] Get bindable devices: source_ieee: [ec:1b:bd:ff:fe:78:3a:89] bindable devices:: [[]]
2020-01-14 13:04:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2922295440] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 134, in _async_get_device_automations
    for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 108, in _async_get_device_automations_from_domain
    return await getattr(platform, function_name)(hass, device_id)
  File "/usr/src/homeassistant/homeassistant/components/zha/device_trigger.py", line 65, in async_get_triggers
    zha_device = await async_get_zha_device(hass, device_id)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/helpers.py", line 142, in async_get_zha_device
    return zha_gateway.devices[ieee]
KeyError: 00:0d:6f:00:0b:5d:d1:25
2020-01-14 13:04:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2922295440] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 134, in _async_get_device_automations
    for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 108, in _async_get_device_automations_from_domain
    return await getattr(platform, function_name)(hass, device_id)
  File "/usr/src/homeassistant/homeassistant/components/zha/device_action.py", line 59, in async_get_actions
    zha_device = await async_get_zha_device(hass, device_id)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/helpers.py", line 142, in async_get_zha_device
    return zha_gateway.devices[ieee]
KeyError: 00:0d:6f:00:0b:5d:d1:25
```

**Database (SELECT * FROM "devices")**
```
00:0d:6f:00:12:35:22:91	0	2
00:15:8d:00:03:67:3f:64	48517	2
00:15:8d:00:02:75:33:5b	4169	2
00:15:8d:00:02:53:70:bc	42031	2
00:15:8d:00:02:75:32:10	24124	2
00:15:8d:00:03:03:3d:99	46212	2
00:15:8d:00:02:37:8a:ca	59174	2
ec:1b:bd:ff:fe:78:31:0a	18553	2
ec:1b:bd:ff:fe:78:3a:89	62600	2
```

**Database (SELECT * FROM "endpoints")**
```
00:0d:6f:00:12:35:22:91	1	260	48879	1
00:15:8d:00:03:67:3f:64	1	260	24321	1
00:15:8d:00:02:75:33:5b	1	260	24321	1
00:15:8d:00:02:53:70:bc	1	260	24321	1
00:15:8d:00:02:75:32:10	1	260	24321	1
00:15:8d:00:03:03:3d:99	1	260	260	1
00:15:8d:00:02:37:8a:ca	1	260	24321	1
00:15:8d:00:02:37:8a:ca	2	260	24322	1
00:15:8d:00:02:37:8a:ca	3	260	24323	1
ec:1b:bd:ff:fe:78:31:0a	1	260	1026	1
ec:1b:bd:ff:fe:78:3a:89	1	260	1026	1
```

**Comment by Adminiuga** [comment]
what radio?

**Comment by shortbloke** [comment]
@Adminiuga The Zigbee transceiver is a Nortek HUSBZB-1 USB

**Comment by shortbloke** [comment]
Created issue with additional debug logs against bellows project: https://github.com/zigpy/bellows/issues/207
