### ISSUE TITLE
Home assistant and Zigate : Device is partially initialized

### ISSUE THREAD

**Issue by bckthomas** [zigpy/zigpy#824]
Hi
I have this warning in the Home assistant logs : 
Device is partially initialized: <ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:01:ed:a6:32 is_initialized=False>
Is it something to be worry about ?
Thanks

Home Assistant v2021.10.0

**Comment by MattWestb** [comment]
Try rejoining the device without deleting it (reset / bring it in pairing mode and have ZHA open for joining devices) and see if ZHA can initializing it OK and if its not working deleting it in ZHA an waiting 2 minutes and then paring it a gen.

The reason for it  is that is that ZHA was not getting all data OK from the device then it was paired and the new version is doing more checks to finding devices that is not OK in the database.

What device is it ?

**Comment by MattWestb** [comment]
Can you see the IEEE address ?
It can giving one clue witch device it is.
All unknown devices shall being your "normal" devices so is you is missing one do the reset and adding it one more time.

**Comment by bckthomas** [comment]
I found the device with the log : ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:01:ed:a6:32 is_initialized=False
The IEEE address is my zigbee coordinator. Maybe I have an issue whith it

**Comment by JeroLajHub** [comment]
Hi, for your information, I still got the same warning with ZiGate USB-TTL 3.21 at every start of the Home Assistant, at its latest updates.

**Comment by puddly** [comment]
Should have been fixed a few months ago.

**Comment by freeasabeer** [comment]
Same kind of issue here:
2022-10-26 19:41:35.971 WARNING (MainThread) [zigpy.application] Device is partially initialized: <ZiGateDevice model='ZiGate USB-TTL 3.23' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:02:1e:2c:3f is_initialized=False>
2022-10-26 19:44:55.938 WARNING (MainThread) [zigpy_zigate.api] Received unhandled response 0x8047: b'08c2'
2022-10-26 19:45:24.912 DEBUG (MainThread) [zigpy_zigate.zigbee.application] Sending packet ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.Broadcast: 15>, address=<BroadcastAddress.ALL_ROUTERS_AND_COORDINATOR: 65532>), dst_ep=0, source_route=None, extended_timeout=False, tsn=9, profile_id=0, cluster_id=<ZDOCmd.Mgmt_Permit_Joining_req: 0x0036>, data=Serialized[b'\t<\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2022-10-26 19:45:24.915 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1618672752] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 317, in websocket_permit_devices
    await zha_gateway.application_controller.permit(time_s=duration, node=ieee)
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 929, in permit
    await zigpy.zdo.broadcast(
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 518, in broadcast
    return await app.broadcast(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 744, in broadcast
    await self.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_zigate/zigbee/application.py", line 244, in send_packet
    (status, tsn, packet_type, _), _ = await self._api.raw_aps_data_request(
AttributeError: 'NoneType' object has no attribute 'raw_aps_data_request'

**Comment by puddly** [comment]
If `self._api` is `None`, your device is not connected.

**Comment by freeasabeer** [comment]
Yes , i had to restart HA to get it working. I don't know what happened.
