### ISSUE TITLE
Iris MOT800 won't join

### ISSUE THREAD

**Issue by xerootg** [zigpy/zigpy#93]
A couple weeks ago I picked up some Iris 1st gen PIR sensors for $6 at Lowes. Today I tried getting them to join and I'm just having one heck of a time getting it to join the network. I can see the sensor attempt to join but it never completes the process. I am running homeassistant 0.82.0 on hassio on a NUC.

I'm guessing a quirk needs to be written for this device, but I'm not sure exactly what i'm looking at to even get started. Can someone point me to whats going on?

Here's the log (I ran HA logging with bellows and zigpy in debug, but removed the bellows lines):
> 2018-11-11 10:19:24 INFO (MainThread) [homeassistant.components.zha] Permitting joins for 60s
2018-11-11 10:19:25 INFO (MainThread) [zigpy.application] Device 0xa372 (00:0d:6f:00:03:b3:1f:d7) joined the network
2018-11-11 10:19:25 INFO (MainThread) [zigpy.device] [0xa372] Discovering endpoints
Config directory: /config
Tries remaining: 3
2018-11-11 10:19:37 INFO (MainThread) [zigpy.application] Device 0x85a7 (00:0d:6f:00:03:b3:1f:d7) joined the network
2018-11-11 10:19:37 DEBUG (MainThread) [zigpy.application] Device 00:0d:6f:00:03:b3:1f:d7 changed id (0xa372 => 0x85a7)
2018-11-11 10:19:37 DEBUG (MainThread) [zigpy.device] Canceling old initialize call
2018-11-11 10:19:37 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 51, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
concurrent.futures._base.CancelledError
2018-11-11 10:19:37 INFO (MainThread) [zigpy.device] [0x85a7] Discovering endpoints
Tries remaining: 3
2018-11-11 10:19:49 INFO (MainThread) [zigpy.application] Device 0x4b8d (00:0d:6f:00:03:b3:1f:d7) joined the network
2018-11-11 10:19:49 DEBUG (MainThread) [zigpy.application] Device 00:0d:6f:00:03:b3:1f:d7 changed id (0x85a7 => 0x4b8d)
2018-11-11 10:19:49 INFO (MainThread) [zigpy.device] [0x4b8d] Discovering endpoints
Tries remaining: 3
Tries remaining: 2
2018-11-11 10:20:02 INFO (MainThread) [zigpy.application] Device 0x2deb (00:0d:6f:00:03:b3:1f:d7) joined the network
2018-11-11 10:20:02 DEBUG (MainThread) [zigpy.application] Device 00:0d:6f:00:03:b3:1f:d7 changed id (0x4b8d => 0x2deb)
2018-11-11 10:20:02 DEBUG (MainThread) [zigpy.device] Canceling old initialize call
2018-11-11 10:20:02 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 51, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
concurrent.futures._base.CancelledError
2018-11-11 10:20:02 INFO (MainThread) [zigpy.device] [0x2deb] Discovering endpoints
Tries remaining: 3
Tries remaining: 1
2018-11-11 10:20:14 INFO (MainThread) [zigpy.application] Device 0x774a (00:0d:6f:00:03:b3:1f:d7) joined the network
2018-11-11 10:20:14 DEBUG (MainThread) [zigpy.application] Device 00:0d:6f:00:03:b3:1f:d7 changed id (0x2deb => 0x774a)
2018-11-11 10:20:14 INFO (MainThread) [zigpy.device] [0x774a] Discovering endpoints
Tries remaining: 3
2018-11-11 10:20:16 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: Message send failure: EmberStatus.DELIVERY_FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 51, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED
Tries remaining: 2
Tries remaining: 2
Tries remaining: 1
2018-11-11 10:20:39 DEBUG (MainThread) [zigpy.zcl] [0x2feb:1:0x0202] ZCL request 0x000a: [[<Attribute attrid=0 value=<zigpy.zcl.foundation.TypeValue object at 0x7f2100189780>>]]
2018-11-11 10:20:39 DEBUG (MainThread) [zigpy.zcl] [0x2feb:1:0x0202] Attribute report received: 0=0
Tries remaining: 1
2018-11-11 10:20:46 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: Message send failure: EmberStatus.DELIVERY_FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 51, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED
2018-11-11 10:20:56 DEBUG (MainThread) [zigpy.zdo] [0x6c34:zdo] ZDO request 0x0000: [00:0d:6f:00:04:26:39:3c, 0, 0]
2018-11-11 10:20:56 DEBUG (MainThread) [zigpy.zcl] [0x6c34:1:0x0006] ZCL request 0x000a: [[<Attribute attrid=0 value=<zigpy.zcl.foundation.TypeValue object at 0x7f20fdb7f4e0>>]]
2018-11-11 10:20:56 DEBUG (MainThread) [zigpy.zcl] [0x6c34:1:0x0006] Attribute report received: 0=Bool.false
2018-11-11 10:20:58 DEBUG (MainThread) [zigpy.zdo] [0x6c34:zdo] ZDO request 0x0000: [00:0d:6f:00:04:26:39:3c, 0, 0]
2018-11-11 10:20:58 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: Message send failure: EmberStatus.DELIVERY_FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 51, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/usr/local/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED

**Comment by Adminiuga** [comment]
Can you try with the HA 0.93.1 and reopen the issue if it doesn't work?
